
/*
 * Universidad del Quindio
 * Lenguaje de Programación
 * Docente: Orlando Herrera
 * Armenia Quindio - 2018
 */
package mybanco.gui.cliente;

import javax.swing.JOptionPane;

/**
 * Esta clase permite la interfaz de cuenta corriente
 *
 * @author Soraya Gonzalez
 * @author Andres Betancourt
 * @version 1.0
 */
public class CuentaCorrienteGUI extends javax.swing.JFrame {

    /**
     * Creates new form CuentaAhorrosGUI
     */
    private PrincipalUsuarioGUI p;

    public CuentaCorrienteGUI(PrincipalUsuarioGUI p) {
        this.p = p;
        initComponents();
        initOtherComponets();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        consignarCuentaCorriente = new javax.swing.JButton();
        bCrearCuentaCorriente = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bRetirarCuentaCorriente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText(".:: Cuentas Corrientes ::.");

        consignarCuentaCorriente.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        consignarCuentaCorriente.setText("Consignar");
        consignarCuentaCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consignarCuentaCorrienteActionPerformed(evt);
            }
        });

        bCrearCuentaCorriente.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        bCrearCuentaCorriente.setText("Crear Cuenta Corriente");
        bCrearCuentaCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearCuentaCorrienteActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton3.setText("Atras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        bRetirarCuentaCorriente.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        bRetirarCuentaCorriente.setText("Retiro Dinero");
        bRetirarCuentaCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRetirarCuentaCorrienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consignarCuentaCorriente, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addComponent(bRetirarCuentaCorriente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(bCrearCuentaCorriente, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addGap(21, 21, 21)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(86, 86, 86)
                .addComponent(consignarCuentaCorriente)
                .addGap(18, 18, 18)
                .addComponent(bRetirarCuentaCorriente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(bCrearCuentaCorriente)
                    .addContainerGap(201, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCrearCuentaCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearCuentaCorrienteActionPerformed
        crearCuentaCorriente();
    }//GEN-LAST:event_bCrearCuentaCorrienteActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        atras();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void consignarCuentaCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consignarCuentaCorrienteActionPerformed
        consignar();
    }//GEN-LAST:event_consignarCuentaCorrienteActionPerformed

    private void bRetirarCuentaCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRetirarCuentaCorrienteActionPerformed
        retirar();
    }//GEN-LAST:event_bRetirarCuentaCorrienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuentaCorrienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuentaCorrienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuentaCorrienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuentaCorrienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCrearCuentaCorriente;
    private javax.swing.JButton bRetirarCuentaCorriente;
    private javax.swing.JButton consignarCuentaCorriente;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
/**
     * Metodo que permite crear Cuenta Corriente
     */
    private void crearCuentaCorriente() {
        String res = p.getLogica().crearCuentaCorriente(p.getTercero());
        if (res != null) {
            //mostrar mensaje aca
            System.out.println("Su Num de Cuenta corriente es " + res + " Por favor no la pierda!");
            JOptionPane.showMessageDialog(p.getContentPane(), "El numero de Cuenta Corriente es " + res + ".\nPor favor anote este numero ya que sera fundamental para realizar transacciones.");

            //persistiendo informacion en archivos
            p.getLogica().persistencia().guardarCuentas(p.getLogica().getCuentas());
        }
    }

    /**
     * Permite retroceder la ventana
     */
    private void atras() {
        this.setVisible(false);
        p.setVisible(true);
        p.cargarTablas();
    }

    private void initOtherComponets() {
        //centrar ventana
        this.setLocationRelativeTo(null);
    }

    /**
     * Permite realizar la accion de consignar en la cuenta corriente
     */
    private void consignar() {
        this.setVisible(false);
        new ConsignarCorrienteGUI(p).setVisible(true);
    }

    /**
     * Permite realizar la accion de retirar en la cuenta
     */
    private void retirar() {
        this.setVisible(false);
        new RetirarCorrienteGUI(p).setVisible(true);
    }

}
