/*
 * Universidad del Quindio
 * Lenguaje de Programación
 * Docente: Orlando Herrera
 * Armenia Quindio - 2018
 */
package mybanco.gui.cliente;

import java.util.Date;
import javax.swing.JOptionPane;
import mybanco.clases.Cuenta;
import mybanco.clases.CuentaAhorros;
import mybanco.utilidades.Fechas;

/**
 * Esta clase contiene la ventana de retirar ahorros
 *
 * @author Soraya Gonzalez
 * @author Andres Betancourt
 * @version 1.0
 */
public class RetirarAhorrosGUI extends javax.swing.JFrame {

    /**
     * Creates new form CuentaAhorrosGUI
     */
    private PrincipalUsuarioGUI p;

    public RetirarAhorrosGUI(PrincipalUsuarioGUI p) {
        this.p = p;
        initComponents();
        initOtherComponets();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bCancelar = new javax.swing.JButton();
        bRetirar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbCuentasAhorros = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cRentabilidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText(".:: Retiro de Ahorros ::.");

        bCancelar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bRetirar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        bRetirar.setText("Retirar");
        bRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRetirarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setText("Numero de Cuenta");

        cbCuentasAhorros.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        cbCuentasAhorros.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCuentasAhorros.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCuentasAhorrosItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setText("Rentabilidad Generada");

        cRentabilidad.setEditable(false);
        cRentabilidad.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                            .addComponent(cbCuentasAhorros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cRentabilidad))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbCuentasAhorros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cRentabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar)
                    .addComponent(bRetirar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        atras();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRetirarActionPerformed
        retirar();
    }//GEN-LAST:event_bRetirarActionPerformed

    private void cbCuentasAhorrosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCuentasAhorrosItemStateChanged
        calcularRentabilidad();
    }//GEN-LAST:event_cbCuentasAhorrosItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RetirarAhorrosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RetirarAhorrosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RetirarAhorrosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RetirarAhorrosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bRetirar;
    private javax.swing.JTextField cRentabilidad;
    private javax.swing.JComboBox cbCuentasAhorros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
/**
     * Metodo que permite crear cuenta de ahorros
     */
    private void crearCuentaAhorros() {
        String res = p.getLogica().crearCuentaAhorros(p.getTercero());
        if (res != null) {
            //mostrar mensaje aca
            System.out.println("Su Num de Cuenta de Ahorros es " + res + " Por favor no la pierda!");
            JOptionPane.showMessageDialog(p.getContentPane(), "El numero de Cuenta de ahorros es " + res + ".\nPor favor anote este numero ya que sera fundamental para realizar transacciones.");

            //persistiendo informacion en archivos
            p.getLogica().persistencia().guardarCuentas(p.getLogica().getCuentas());
        }
    }

    /**
     * Metodo que permite retoceder de ventana
     */
    private void atras() {
        this.setVisible(false);
        p.setVisible(true);
        p.cargarTablas();
    }

    private void initOtherComponets() {
        //centrar pantalla
        setLocationRelativeTo(null);
        //borrar contenido combobox
        cbCuentasAhorros.removeAllItems();
        for (Cuenta c : p.getLogica().cuentasAhorrosUsuario(p.getTercero())) {
            cbCuentasAhorros.addItem(c);
        }
    }

    /**
     * Método que permite validar la exstencia de cuentas de ahorros
     */
    private void retirar() {
        if (cbCuentasAhorros.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Debe tener una cuenta registrada para poder retirar", "No hay cuentas registradas", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Cuenta cuenta = (Cuenta) cbCuentasAhorros.getSelectedItem();
        Double entregar = cuenta.getMonto() + Double.valueOf(cRentabilidad.getText());

        boolean ok = p.getLogica().actualizarMontoCuentaAhorros(cuenta, -cuenta.getMonto(), new Date());

        if (ok) {
            JOptionPane.showMessageDialog(this, "Transaccion Exitosa. se Entregan: $" + entregar, "Retiro Ahorros", JOptionPane.INFORMATION_MESSAGE);
            atras();
        } else {
            JOptionPane.showMessageDialog(this, "No se logro realizar Retiro. Consulte a su Banco", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * MEtodo que permite calcular la rentabiliad de la cuenta de ahorros
     */
    private void calcularRentabilidad() {
        if (cbCuentasAhorros.getSelectedItem() != null) {
            Cuenta c = (Cuenta) cbCuentasAhorros.getSelectedItem();
            Date fCreacion = c.getfCreacion();
            Date fRetiro = new Date();

            int meses = Fechas.mesesEntreFechas(fCreacion, fRetiro);

            Double tasa = 0.03;

            if (c.getMonto() >= 0 && c.getMonto() <= 5000000) {
                tasa = 0.01;
            } else if (c.getMonto() > 5000000 && c.getMonto() <= 20000000) {
                tasa = 0.02;
            }

            Double rentabilidad = c.getMonto() * tasa * meses;

            cRentabilidad.setText(String.valueOf(rentabilidad));
        }

    }

}
