package mybanco.gui.cliente;

import java.util.Date;
import javax.swing.JOptionPane;
import mybanco.clases.Cuenta;
import mybanco.clases.CuentaAhorros;
import mybanco.utilidades.Fechas;

/**
 *
 * @author sori
 */
public class RetirarCorrienteGUI extends javax.swing.JFrame {

    /**
     * Creates new form CuentaAhorrosGUI
     */
    private PrincipalUsuarioGUI p;

    public RetirarCorrienteGUI(PrincipalUsuarioGUI p) {
        this.p = p;
        initComponents();
        initOtherComponets();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bCancelar = new javax.swing.JButton();
        bRetirar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbCuentasCorriente = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cRentabilidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText(".:: Retiro de Cuenta Corriente ::.");

        bCancelar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bRetirar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        bRetirar.setText("Retirar");
        bRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRetirarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setText("Numero de Cuenta");

        cbCuentasCorriente.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        cbCuentasCorriente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCuentasCorriente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCuentasCorrienteItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setText("Valor a Retirar");

        cRentabilidad.setEditable(false);
        cRentabilidad.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setText("Cuota Manejo");

        cValor.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCuentasCorriente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cRentabilidad)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cValor)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbCuentasCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(9, 9, 9)
                .addComponent(cRentabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar)
                    .addComponent(bRetirar))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        atras();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRetirarActionPerformed
        retirar();
    }//GEN-LAST:event_bRetirarActionPerformed

    private void cbCuentasCorrienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCuentasCorrienteItemStateChanged
        calcularCuotaManejo();
    }//GEN-LAST:event_cbCuentasCorrienteItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RetirarCorrienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RetirarCorrienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RetirarCorrienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RetirarCorrienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bRetirar;
    private javax.swing.JTextField cRentabilidad;
    private javax.swing.JTextField cValor;
    private javax.swing.JComboBox cbCuentasCorriente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    private void atras() {
        this.setVisible(false);
        p.setVisible(true);
    }

    private void initOtherComponets() {
        //centrar pantalla
        setLocationRelativeTo(null);
        //borrar contenido combobox
        cbCuentasCorriente.removeAllItems();
        for (Cuenta c : p.getLogica().cuentasCorrientesUsuario(p.getTercero())) {
            cbCuentasCorriente.addItem(c);
        }
    }

    private void retirar() {
        if (cbCuentasCorriente.getSelectedItem() == null ) {
            JOptionPane.showMessageDialog(this, "Debe tener una cuenta registrada para poder retirar", "No hay cuentas registradas", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Cuenta cuenta = (Cuenta) cbCuentasCorriente.getSelectedItem();
        Double montoSolicitado = Double.valueOf(cValor.getText());
        
        if(montoSolicitado > cuenta.getMonto()){
             JOptionPane.showMessageDialog(this, "Saldo Insuficiente. Cuenta con $"+cuenta.getMonto() + " en la cuenta.", "Sin Fondos", JOptionPane.ERROR_MESSAGE);
            return;
        }
       
       
        boolean ok = p.getLogica().actualizarMontoCuentaCorriente(cuenta, -montoSolicitado);

        if (ok) {
            JOptionPane.showMessageDialog(this, "Transaccion Exitosa. se Entregan: $"+montoSolicitado, "Retiro Cuenta Corriente", JOptionPane.INFORMATION_MESSAGE);
            setVisible(false);
            p.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No se logro realizar Retiro. Consulte a su Banco", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * Este metodo permite calcular cuota de manejo
     */
    private void calcularCuotaManejo() {
        if (cbCuentasCorriente.getSelectedItem() != null) {
            Cuenta c = (Cuenta) cbCuentasCorriente.getSelectedItem();            
            cRentabilidad.setText(String.valueOf(Cuenta.CUOTA_MANEJO));
        }
    }

}
