package mybanco.gui.empresa;

import javax.swing.JOptionPane;
import mybanco.clases.Cliente;
import mybanco.clases.Cuenta;

/**
 *
 * @author sori
 */
public class ConsignarNominaGUI extends javax.swing.JFrame {

    /**
     * Creates new form CuentaAhorrosGUI
     */
    private PrincipalEmpresaGUI p;

    public ConsignarNominaGUI(PrincipalEmpresaGUI p) {
        this.p = p;
        initComponents();
        initOtherComponets();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bCancelar = new javax.swing.JButton();
        bConsignar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbEmpleados = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cValor = new javax.swing.JTextField();
        cCuenta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText(".:: Consignar a Nomina ::.");

        bCancelar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bConsignar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        bConsignar.setText("Consignar");
        bConsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsignarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setText("Empleado");

        cbEmpleados.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        cbEmpleados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEmpleados.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEmpleadosItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setText("Valor a Depositar");

        cValor.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        cCuenta.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setText("Numero Cuenta Empresarial");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bConsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                            .addComponent(cbEmpleados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cValor)
                            .addComponent(cCuenta))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar)
                    .addComponent(bConsignar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        atras();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bConsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsignarActionPerformed
        consignar();
    }//GEN-LAST:event_bConsignarActionPerformed

    private void cbEmpleadosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEmpleadosItemStateChanged
        obtenerCuentaEmpleado();
    }//GEN-LAST:event_cbEmpleadosItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsignarNominaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsignarNominaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsignarNominaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsignarNominaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bConsignar;
    private javax.swing.JTextField cCuenta;
    private javax.swing.JTextField cValor;
    private javax.swing.JComboBox cbEmpleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    private void crearCuentaAhorros() {
        String res = p.getLogica().crearCuentaAhorros(p.getTercero());
        if (res != null) {
            //mostrar mensaje aca
            System.out.println("Su Num de Cuenta de Ahorros es " + res + " Por favor no la pierda!");
            JOptionPane.showMessageDialog(p.getContentPane(), "El numero de Cuenta de ahorros es " + res + ".\nPor favor anote este numero ya que sera fundamental para realizar transacciones.");

            //persistiendo informacion en archivos
            p.getLogica().persistencia().guardarCuentas(p.getLogica().getCuentas());
        }
    }

    private void atras() {
        this.setVisible(false);
        p.setVisible(true);
    }

    private void initOtherComponets() {
        //centrar pantalla
        setLocationRelativeTo(null);
        //borrar contenido combobox
        cbEmpleados.removeAllItems();
        for (Cliente c : p.getLogica().getClientes()) {
            cbEmpleados.addItem(c);
        }
    }

    private void consignar() {
        if (cbEmpleados.getSelectedItem() == null || cValor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe diligenciar los campos para realizar Registro", "Cambos Vacios", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (cCuenta.getText() == null){
            JOptionPane.showMessageDialog(this, "Debe crear cuenta nomina a Empleado para poder depositar", "No existe cuenta", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Double valorConsignar = Double.valueOf(cValor.getText());
       
        boolean ok = p.getLogica().actualizarMontoCuentaNomina(cCuenta.getText(), valorConsignar);

        if (ok) {
            JOptionPane.showMessageDialog(this, "Transaccion Exitosa.", "Consignacion Nomina", JOptionPane.INFORMATION_MESSAGE);
            setVisible(false);
            p.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No se logro realizar consignacion. Consulte a su Banco", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void obtenerCuentaEmpleado() {
        if (cbEmpleados.getSelectedItem() != null) {
            Cliente empleado = (Cliente) cbEmpleados.getSelectedItem();
            
            String cuenta = p.getLogica().obtenerNumCuentaNomina(empleado);
            if(cuenta != null){
                cCuenta.setText(cuenta);
            }else{
                JOptionPane.showMessageDialog(this, "Al parecer el usuario no tiene creada ninguna cuenta de nomina", "No se encontro cuenta.", JOptionPane.ERROR_MESSAGE);
                cCuenta.setText("");
            }          
        }
    }

}
